apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: network-flask-backend
  name: flask-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: network-flask-backend
  strategy: {}
  template:
    metadata:
      labels:
        app: network-flask-backend
    spec:
      containers:
      - image: 649671357648.dkr.ecr.us-east-1.amazonaws.com/network-flask-app:latest
        name: flask-app
        ports:
        - containerPort: 8080
        resources: {}
status: {}
